### ISSUE TITLE
4.0+ lacks ->xslt

### ISSUE THREAD

**Issue by tomascohen** [LibreCat/perl-oai-lib#4]
On our project, we have this code:

```
    $response->set_handler( XML::SAX::Writer->new( Output => *STDOUT ) );
    $response->xslt( "/path/to/OAI.xslt" );
    $response->generate;
```

It works correctly with 3.26. We want to support the 4.0+ API. But it seems the xslt method is no longer exported as it was previously, only in:

```
 lib/HTTP/OAI/Response.pm:63:sub xslt { shift->headers->header('xslt',@_) })
```
I would also like to talk about what's changed between v3 and v4.

**Comment by phochste** [comment]
Indeed, the xslt method was missing these responses. But the syntax how to process XML also has been changed between version 3.26 and the current 4.0+ versions. In `t/getrecord.t` you can see an example how your code should be written with the `generate` method.
